spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/pathfinder_db?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: root
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 20000
      max-lifetime: 1800000

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  sql:
    init:
      mode: never

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
